// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDLLA2cwZvYBLLbGzoQG1WuHqZJihvUvo',
    appId: '1:325616474817:android:d6ca576fd09adc93511240',
    messagingSenderId: '325616474817',
    projectId: 'todo-app-8cf9b',
    storageBucket: 'todo-app-8cf9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu5moabQMFX3XbegtKB3gJp87bOnZ30sk',
    appId: '1:325616474817:ios:55345d461ae8f96f511240',
    messagingSenderId: '325616474817',
    projectId: 'todo-app-8cf9b',
    storageBucket: 'todo-app-8cf9b.appspot.com',
    iosBundleId: 'com.app.todoapp.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcMnN_z4ZmjvMMI2f6DgYEgZ-9_vuQtMc',
    appId: '1:325616474817:web:16767aa700727bad511240',
    messagingSenderId: '325616474817',
    projectId: 'todo-app-8cf9b',
    authDomain: 'todo-app-8cf9b.firebaseapp.com',
    storageBucket: 'todo-app-8cf9b.appspot.com',
  );
}
